apiVersion: v1
name: prometheus-operator
description: prometheus-operator chart that runs on kubernetes
version: 1.0.8
keywords:
  - prometheus-operator
  - kubernetes
home: https://github.com/stakater-charts/prometheus-operator
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io